export 'authentication_repository.dart';
export 'post_meta_repository.dart';
export 'bookmark_repository.dart';
export 'comment_repository.dart';
export 'following_repository.dart';
export 'forex_repository.dart';
export 'horoscope_repository.dart';
export 'news_repository.dart';
export 'corona_repository.dart';
