Map<String, String> forexCurrencies = {
  'INR': 'Indian Rupee',
  'USD': 'U.S. Dollar',
  'EUR': 'European Euro',
  'GBP': 'UK Pound Sterling',
  'CHF': 'Swiss Franc',
  'AUD': 'Australian Dollar',
  'CAD': 'Canadian Dollar',
  'SGD': 'Singapore Dollar',
  'JPY': 'Japanese Yen',
  'CNY': 'Chinese Yuan',
  'SAR': 'Saudi Arabian Riyal',
  'QAR': 'Qatari Riyal',
  'THB': 'Thai Baht',
  'AED': 'UAE Dirham',
  'MYR': 'Malaysian Ringgit',
  'KRW': 'South Korean Won',
  'SEK': 'Swedish Kroner',
  'DKK': 'Danish Kroner',
  'HKD': 'Hong Kong Dollar',
  'KWD': 'Kuwaity Dinar',
  'BHD': 'Bahrain Dinar',
};
